name: Advent of Code 2018 (Bash)
on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Setup tools
      run: |
        sudo apt-get install shellcheck ucspi-tcp -y
        
        # Install BATS
        git clone https://github.com/bats-core/bats-core.git
        cd bats-core
        sudo ./install.sh /usr/local
        
    - uses: actions/checkout@v2
      
    - name: Run tests
      run: make test-aoc2018
