name: Backend (Rust)
on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install minimal nightly with clippy and rustfmt
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        
    - uses: actions/checkout@v2
    
    - name: Build
      run: make build-backend
      
    - name: Run tests
      run: make test-backend
